config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  get 'pages/private'

  get 'auth/developer', :as => 'developer_auth'
  get 'auth/github', :as => 'github_auth'
  match 'auth/:provider/callback' => 'session#create', :via => [:get, :post]

  get 'session/destroy', :as => 'logout'

  get 'repo/index'
  get 'repo/more'
  get 'repo/stargazers'
  get 'repo/more-stargazers'
  get 'repo/issues'
  get 'repo/more-issues'
  # get 'repo/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/controllers/repo_controller.rb
class RepoController < ApplicationController

    RepositoryQuery = Demo::Client.parse <<-'GRAPHQL'
		query($login: String!) {
		  	repositoryOwner(login: $login) {
			    repositories(first: 30) {
				   	totalCount
				    edges {
				        cursor
				        node {
					        ... on Repository {
						        name
						        stargazers(first: 2) {
						            totalCount
						            nodes {
						              	... on User {
						                	name
						              	}
						            }
						        }
						        issues(first: 2) {
						            totalCount
						            nodes {
						              	... on Issue {
						                	body
						              	}
						            }
						        }
					        }
					    }
				    }
			      	pageInfo {
	      				startCursor
						endCursor
						hasPreviousPage
						hasNextPage
					}

			    }
			  }
		}


    GRAPHQL

  	def index
  		@search = params[:search]
  		# @page = params.fetch(:page, 0).to_i


  		if params[:search] == nil
  			@works = nil
  		else
  			login = params[:search]
  			resultRepo = Demo::Client.query(RepositoryQuery, variables: { login: login })

  			if resultRepo.data.repository_owner == nil 
  				@works = nil
  			else
  				@works = resultRepo.data.repository_owner.repositories
  			end
  			
  		end
  		
 	end  	


	 # Define query for "Show more repositories..." AJAX action.
  	MoreQueryRepo = Demo::Client.parse <<-'GRAPHQL'
	    query($login: String!, $after: String!) {
	      repositoryOwner(login: $login) {
			    repositories(first: 30, after: $after) {
				   	totalCount
				    edges {
				        cursor
				        node {
					        ... on Repository {
						        name
						        stargazers(first: 2) {
						            totalCount
						            nodes {
						              	... on User {
						                	name
						              	}
						            }
						        }
						        issues(first: 2) {
						            totalCount
						            nodes {
						              	... on Issue {
						                	body
						              	}
						            }
						        }
					        }
					    }
				    }
			      	pageInfo {
	      				startCursor
						endCursor
						hasPreviousPage
						hasNextPage
					}

			    }
			}
	    }
  GRAPHQL

  # GET /repositories/more?after=CURSOR
  def more
    # Execute the MoreQuery passing along data from params to the query.
    resultRepo = Demo::Client.query(MoreQueryRepo, variables: { login: params[:search], after: params[:after] })
    @works = resultRepo.data.repository_owner.repositories
    @search = params[:search]
    # Using an explicit render again, just render the repositories list partial
    # and return it to the client.
    render partial: "repo"
  end

  	QueryStargazers = Demo::Client.parse <<-'GRAPHQL'
	    query($login: String!, $name: String!){
		  repositoryOwner (login: $login) {
		    repository(name: $name) {
		      stargazers(first: 30) {
		        totalCount
		        edges {
					    cursor
			              	node {
			          			... on User {
			            			name
			          			}
			        		}
			        	}
		          	pageInfo {
		                startCursor
			            endCursor
			            hasPreviousPage
			            hasNextPage
					}
		      	}
		    }
		  }
		}
  	GRAPHQL

  	def stargazers
	    # Execute the MoreQuery passing along data from params to the query.
	    resultStargazers = Demo::Client.query(QueryStargazers, variables: { login: params[:search], name: params[:name] })
	    @works = resultStargazers.data.repository_owner.repository
	    # @search = params[:search]
	    # Using an explicit render again, just render the repositories list partial
	    # and return it to the client.
	    render partial: "stargazers"
  	end

  	MoreQueryStargazers = Demo::Client.parse <<-'GRAPHQL'
	    query($login: String!, $name: String!, $after: String!){
		  repositoryOwner (login: $login) {
		    repository(name: $name) {
		      stargazers(first: 30, after: $after) {
		        totalCount
		        edges {
					    cursor
			              	node {
			          			... on User {
			            			name
			          			}
			        		}
			        	}
		          	pageInfo {
		                startCursor
			            endCursor
			            hasPreviousPage
			            hasNextPage
					}
		      	}
		    }
		  }
		}
  	GRAPHQL

  	def more_stargazers
	    # Execute the MoreQuery passing along data from params to the query.
	    resultStargazers = Demo::Client.query(MoreQueryStargazers, variables: { login: params[:search], name: params[:name], after: params[:after] })
	    @works = resultStargazers.data.repository_owner.repository
	    # @search = params[:search]
	    # Using an explicit render again, just render the repositories list partial
	    # and return it to the client.
	    render partial: "stargazers"
  	end

  	QueryIssues = Demo::Client.parse <<-'GRAPHQL'
	    query($login: String!, $name: String!){
		  repositoryOwner (login: $login) {
		    repository(name: $name) {
		      issues(first: 30) {
		        totalCount
		        edges {
					    cursor
			              	node {
			          			... on Issue {
			            			body
			          			}
			        		}
			        	}
		          	pageInfo {
		                startCursor
			            endCursor
			            hasPreviousPage
			            hasNextPage
					}
		      	}
		    }
		  }
		}
  	GRAPHQL

  	def issues
  		# Execute the MoreQuery passing along data from params to the query.
	    resultIssues = Demo::Client.query(QueryIssues, variables: { login: params[:search], name: params[:name] })
	    @works = resultIssues.data.repository_owner.repository
	    # @search = params[:search]
	    # Using an explicit render again, just render the repositories list partial
	    # and return it to the client.
	    render partial: "issues"
  	end

  	MoreQueryIssues = Demo::Client.parse <<-'GRAPHQL'
	    query($login: String!, $name: String!, $after: String!){
		  repositoryOwner (login: $login) {
		    repository(name: $name) {
		      issues(first: 30, after: $after) {
		        totalCount
		        edges {
					    cursor
			              	node {
			          			... on Issue {
			            			body
			          			}
			        		}
			        	}
		          	pageInfo {
		                startCursor
			            endCursor
			            hasPreviousPage
			            hasNextPage
					}
		      	}
		    }
		  }
		}
  	GRAPHQL

  	def more_issues
  		# Execute the MoreQuery passing along data from params to the query.
	    resultIssues = Demo::Client.query(MoreQueryIssues, variables: { login: params[:search], name: params[:name], after: params[:after] })
	    @works = resultIssues.data.repository_owner.repository
	    # @search = params[:search]
	    # Using an explicit render again, just render the repositories list partial
	    # and return it to the client.
	    render partial: "issues"
  	end

end

app/helpers/repo_helper.rb
module RepoHelper
end

app/views/repo/_issues.html.erb
<% if  @works != nil %>
  <% @works.issues.edges.each do |work|%>
    <li class="list-group-item">
    	<%= work.node.body%>
    	<% if work.node.body == nil %>
  	  <p> BODY NULL </p>
  	<% else %>
    		<p><%= work.node.body%></p>
    	<% end %>  

    </li>
    <li class="disabled-none"><%= work.cursor%></li>
  <% end %>
  <% if @works.issues.page_info.has_next_page == false %>
  	<li class="disabled-none"><%= false %></li>
  <% end %>  
<% else %>
 <li><p>NOT DATA</p></li>
<% end %>  

app/views/repo/_repo.html.erb
<% if @works == nil %>
  <h1> Not data </h1>
<% else %>

	<% @works.edges.each do |work|%>
	  <tr>
	  	  <td class="" hidden="true" id="repo-cursor"><p><%= work.cursor%></p></td>
	  	  <td style="width: 10%" > <p><%= work.node.stargazers.total_count%></p></td>
	      <td style="width: 10%" > <p><%= work.node.name%></p></td>
	      <td style="width: 20%" >
	      	<% if work.node.stargazers.total_count != 0 %>
				<ul id="list-stargazers-<%= work.node.name%>" class="list-group list-stargazers-<%= work.node.name%>">

				</ul>
			     <a class="js-load-stargazers" href="<%= repo_stargazers_path(search:@search, name: work.node.name) %>">
		          <button id="btn-load-stargazers-<%= work.node.name%>" class=" btn btn-primary btn-sm">
		           Load Stargazers
		             <span class="octicon octicon-sync spinner"></span>
		          </button>
		        </a>

		        <a id="btn-load-more-stargazers-<%= work.node.name%>" class="js-load-more-stargazers disabled-none" href="<%= repo_more_stargazers_path(search:@search, name: work.node.name, after: "") %>">
		          <button  class=" btn btn-primary btn-sm">
		           Load More Stargazers
		             <span class="octicon octicon-sync spinner"></span>
		          </button>
		        </a>
	        <% end %>  

	      </td>
	      <td style="width: 60%">
	      	<% if work.node.issues.total_count != 0 %>
	      		<ul id="list-issues-<%= work.node.name%>" class="list-group list-issues-<%= work.node.name%>">

				</ul>
			     <a class="js-load-issues" href="<%= repo_issues_path(search:@search, name: work.node.name) %>">
		          <button id="btn-load-issues-<%= work.node.name%>" class=" btn btn-primary btn-sm">
		           Load Issues
		             <span class="octicon octicon-sync spinner"></span>
		          </button>
		        </a>

		        <a id="btn-load-more-issues-<%= work.node.name%>" class="js-load-more-issues disabled-none" 
		        	href="<%= repo_more_issues_path(search:@search, name: work.node.name, after: "") %>">
		          <button  class=" btn btn-primary btn-sm">
		           Load More Issue
		             <span class="octicon octicon-sync spinner"></span>
		          </button>
		        </a>
	      	<% end %>  
	    </tr>
	<% end %>
<% end %>

<% if  @works != nil && !@works.page_info.has_next_page %>
  <p id="load-more-repo" class="disabled-none">false</p>
<% end %>

app/views/repo/_stargazers.html.erb
<% @works.stargazers.edges.each do |work|%>
  <li class="list-group-item">
  	<% if work.node.name == nil %>
	  <p> NAME NULL </p>
	<% else %>
  		<p><%= work.node.name%></p>
  	<% end %>  

  </li>
  <li class="disabled-none"><%= work.cursor%></li>
<% end %>
<% if @works.stargazers.page_info.has_next_page == false %>
	<li class="disabled-none"><%= false %></li>
<% end %>  

app/views/repo/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/sticky-footer-navbar.css">


    <style type="text/css">
      .disabled-link {
      pointer-events: none;
    }

    .disabled-none {
      display: none;
    }
    .disabled-show {
      display: block;
    }
    </style>

    <title>Hello, world!</title>
  </head>
  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="<%= pages_private_path %>">Demo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%= repo_index_path %>">Repo <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <%= link_to "Logout", :logout %>
        </div>
      </nav>
    </header>



    <!-- Begin page content -->
    <main role="main" class="container">
      <h1 class="mt-5">Repository</h1>

      <%= form_tag repo_index_path, :method => 'get' do %>
  		  <%= label_tag(:search, "Search for:") %>
  		  <%= text_field_tag(:search, @search )%>
  		  <%= submit_tag("Search") %>
		  <% end %>
    	
      <!-- 	<form class="form-inline md-form mr-auto mb-4">
      		<p>User or Organization </title>
		  	<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
		  	<button class="btn btn-primary btn-sm" type="submit">Search</button>
		</form> -->

      <table class="table table-hover" id="table-repositories">
  		  <thead>
  		    <tr>
            <th scope="col">Stargazers total</th>
  		      <th scope="col">Name</th>
  		      <th scope="col">Load stargazers</th>
             <th scope="col">Load issue</th>
  		    </tr>
  		  </thead>
  		  <tbody>
  		  	 <%= render "repo", works: @works, search: @search %>
  		  </tbody>
		</table>


    <% if @works != nil && @works.page_info.has_next_page?  %>
      
        <a class="js-load-more" href="<%= repo_more_path(search:@search, after: @works.edges.last.cursor) %>">
          <button id="btn-repo-load-more" class=" btn btn-primary btn-sm">
            Load more
             <span class="octicon octicon-sync spinner"></span>
          </button>
        </a>
       
    <% end %>
  </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Code demo by NGUYEN XUAN KHANH 2020</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

	</body>
</html>